services:
  ollama: 
    container_name: ollama
    build:
      context: .
      dockerfile: DockerfileOllama
    ports:
      - "11434:11434"
  tourish: 
    container_name: tourish
    depends_on:
      - ollama
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - "3000:3000"