INSERT INTO accounts (userName, password, citizenID, name, address, age, telNum, email) VALUES ("exampleUser1","password1","VN23192748","User1","Random address",18,"125-215-2678","anything1@gmail.com")
INSERT INTO accounts (userName, password, citizenID, name, address, age, telNum, email) VALUES ("exampleUser2","password2","VN23192748","User2","Random address",18,"125-215-2678","anything2@gmail.com")
INSERT INTO accounts (userName, password, citizenID, name, address, age, telNum, email) VALUES ("exampleUser3","password3","VN23192748","User3","Random address",18,"125-215-2678","anything3@gmail.com")
INSERT INTO accounts (userName, password, citizenID, name, address, age, telNum, email) VALUES ("exampleUser4","password4","VN23192748","User4","Random address",18,"125-215-2678","anything4@gmail.com")
INSERT INTO accounts (userName, password, citizenID, name, address, age, telNum, email) VALUES ("exampleUser5","password5","VN23192748","User5","Random address",18,"125-215-2678","anything5@gmail.com")

INSERT INTO transportations (Name, startDate, endDate, price, goFrom, arriveAt, type) VALUES("P3123","5-6-2024","7-6-2024",10,"Station 1 Port A","Station 1 Port B","Plane")
INSERT INTO transportations (Name, startDate, endDate, price, goFrom, arriveAt, type) VALUES("P231","5-6-2024","7-6-2024",10,"Station 2 Port A","Station 2 Port B","Plane")
INSERT INTO transportations (Name, startDate, endDate, price, goFrom, arriveAt, type) VALUES("B3213","5-6-2024","8-6-2024",120,"Station 3 Port A","Station 1 Port B","Bus")
INSERT INTO transportations (Name, startDate, endDate, price, goFrom, arriveAt, type) VALUES("C31257","5-6-2024","7-6-2024",130,"Station 2 Port A","Station 4 Port B","Coach")
INSERT INTO transportations (Name, startDate, endDate, price, goFrom, arriveAt, type) VALUES("P2937","5-6-2024","8-6-2024",110,"Station 11 Port A","Station 12 Port B","Plane")
INSERT INTO transportations (Name, startDate, endDate, price, goFrom, arriveAt, type) VALUES("B3213","5-6-2024","5-6-2024",120,"Station 12 Port A","Station 31 Port B","Coach")
INSERT INTO transportations (Name, startDate, endDate, price, goFrom, arriveAt, type) VALUES("B3213","5-6-2024",null,110,"Station 13 Port A","Station 11 Port B","Boat")
INSERT INTO transportations (Name, startDate, endDate, price, goFrom, arriveAt, type) VALUES("B7695","5-6-2024",null,130,"Station 14 Port A","Station 11 Port B","Plane","Bus")
INSERT INTO transportations (Name, startDate, endDate, price, goFrom, arriveAt, type) VALUES("C3945","5-6-2024","5-6-2024",120,"Station 11 Port A","Station 21 Port B","Coach")
INSERT INTO transportations (Name, startDate, endDate, price, goFrom, arriveAt, type) VALUES("C4526","5-6-2024","5-6-2024",190," tation 21 Port A","Station 31 Port B","Coach")


INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(1,"Tour 1", "What ever", 10,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(2,"Tour 2", "What ever", 20,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(3,"Tour 3", "What ever", 30,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(4,"Tour 4", "What ever", 20,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(5,"Tour 5", "What ever", 15,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(6,"Tour 6", "What ever", 16,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(7,"Tour 7", "What ever", 11,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(8,"Tour 8", "What ever", 103,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(9,"Tour 9", "What ever", 102,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(10,"Tour 10", "What ever", 104,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(11,"Tour 11", "What ever", 102,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(12,"Tour 12", "What ever", 120,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(13,"Tour 13", "What ever", 110,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(14,"Tour 14", "What ever", 130,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(15,"Tour 15", "What ever", 120,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(16,"Tour 16", "What ever", 140,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(17,"Tour 17", "What ever", 150,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(18,"Tour 18", "What ever", 170,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(19,"Tour 19", "What ever", 110,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(20,"Tour 20", "What ever", 120,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(21,"Tour 21", "What ever", 130,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(22,"Tour 22", "What ever", 140,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(23,"Tour 23", "What ever", 110,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(24,"Tour 24", "What ever", 210,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(25,"Tour 25", "What ever", 410,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(26,"Tour 26", "What ever", 610,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(27,"Tour 27", "What ever", 130,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(28,"Tour 28", "What ever", 120,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(29,"Tour 29", "What ever", 1012,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(30,"Tour 30", "What ever", 103,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(31,"Tour 31", "What ever", 10794,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(32,"Tour 32", "What ever", 106,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(33,"Tour 33", "What ever", 104,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(34,"Tour 34", "What ever", 105,"something.jgp",null)
INSERT INTO tours (townID, tourName, description, price, images, transportationID) VALUES(35,"Tour 35", "What ever", 1043,"something.jgp",null)

INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 1", "5-6-2024" ,"6-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 2", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 3", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 4", "5-6-2024" ,"6-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 5", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 6", "5-6-2024" ,"8-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 7", "5-6-2024" ,"8-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 8", "5-6-2024" ,"8-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 9", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 10", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 11", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 12", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 13", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 14", "5-6-2024" ,"1-7-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 15", "5-6-2024" ,"1-7-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 16", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 17", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 18", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 19", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 20", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 21", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 22", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 23", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 24", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 25", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 26", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 27", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 28", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 29", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 30", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 31", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 32", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 33", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 34", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 35", "5-6-2024" ,"5-6-2024")

INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 1", "6-6-2024" ,"6-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 2", "6-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 3", "6-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 4", "7-6-2024" ,"6-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 5", "7-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 6", "7-6-2024" ,"8-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 7", "6-6-2024" ,"8-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 8", "7-6-2024" ,"8-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 9", "8-6-2024" ,"10-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 10", "6-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 11", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 12", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 13", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 14", "5-6-2024" ,"1-7-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 15", "5-6-2024" ,"1-7-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 16", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 17", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 18", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 19", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 20", "7-6-2024" ,"10-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 21", "8-6-2024" ,"8-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 22", "9-6-2024" ,"10-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 23", "7-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 24", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 25", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 26", "5-6-2024" ,"7-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 27", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 28", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 29", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 30", "5-6-2024" ,"9-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 31", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 32", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 33", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 34", "5-6-2024" ,"5-6-2024")
INSERT INTO tour_date (townID, tourName, description, price, images, transportationID) VALUES("Tour 35", "5-6-2024" ,"5-6-2024")


